### ISSUE TITLE
每次运行到epoch5就开始报错

### ISSUE THREAD

**Issue by ABCD121-SOURCE** [justchenhao/STANet#100]
learning rate = 0.0002000
(epoch: 5, iters: 20, time: 0.062, data: 0.001) f: 23.105 
(epoch: 5, iters: 120, time: 0.063, data: 0.001) f: 110.492 
(epoch: 5, iters: 220, time: 0.061, data: 0.000) f: 49.779 
(epoch: 5, iters: 320, time: 0.061, data: 0.000) f: 23.528 
(epoch: 5, iters: 420, time: 0.060, data: 0.001) f: 91.624 
(epoch: 5) current_t_epoch: 24.592 
saving the model at the end of epoch 5, iters 2225
changedetection
['D:\\project2\\test2\\train\\A\\train_1.png', 'D:\\project2\\test2\\train\\A\\train_10.png', 'D:\\project2\\test2\\train\\A\\train_100.png', 'D:\\project2\\test2\\train\\A\\train_101.png', 'D:\\project2\\test2\\train\\A\\train_102.png', 'D:\\project2\\test2\\train\\A\\train_103.png', 'D:\\project2\\test2\\train\\A\\train_104.png', 'D:\\project2\\test2\\train\\A\\train_105.png', 'D:\\project2\\test2\\train\\A\\train_106.png', 'D:\\project2\\test2\\train\\A\\train_107.png', 'D:\\project2\\test2\\train\\A\\train_108.png', 'D:\\project2\\test2\\train\\A\\train_109.png', 'D:\\project2\\test2\\train\\A\\train_11.png', 'D:\\project2\\test2\\train\\A\\train_110.png', 'D:\\project2\\test2\\train\\A\\train_111.png', 'D:\\project2\\test2\\train\\A\\train_112.png', 'D:\\project2\\test2\\train\\A\\train_113.png', 'D:\\project2\\test2\\train\\A\\train_114.png', 'D:\\project2\\test2\\train\\A\\train_115.png', 'D:\\project2\\test2\\train\\A\\train_116.png', 'D:\\project2\\test2\\train\\A\\train_117.png', 'D:\\project2\\test2\\train\\A\\train_118.png', 'D:\\project2\\test2\\train\\A\\train_119.png', 'D:\\project2\\test2\\train\\A\\train_12.png', 'D:\\project2\\test2\\train\\A\\train_120.png', 'D:\\project2\\test2\\train\\A\\train_121.png', 'D:\\project2\\test2\\train\\A\\train_122.png', 'D:\\project2\\test2\\train\\A\\train_123.png', 'D:\\project2\\test2\\train\\A\\train_124.png', 'D:\\project2\\test2\\train\\A\\train_125.png', 'D:\\project2\\test2\\train\\A\\train_126.png', 'D:\\project2\\test2\\train\\A\\train_127.png', 'D:\\project2\\test2\\train\\A\\train_128.png', 'D:\\project2\\test2\\train\\A\\train_129.png', 'D:\\project2\\test2\\train\\A\\train_13.png', 'D:\\project2\\test2\\train\\A\\train_130.png', 'D:\\project2\\test2\\train\\A\\train_131.png', 'D:\\project2\\test2\\train\\A\\train_132.png', 'D:\\project2\\test2\\train\\A\\train_133.png', 'D:\\project2\\test2\\train\\A\\train_134.png', 'D:\\project2\\test2\\train\\A\\train_135.png', 'D:\\project2\\test2\\train\\A\\train_136.png', 'D:\\project2\\test2\\train\\A\\train_137.png', 'D:\\project2\\test2\\train\\A\\train_138.png', 'D:\\project2\\test2\\train\\A\\train_139.png', 'D:\\project2\\test2\\train\\A\\train_14.png', 'D:\\project2\\test2\\train\\A\\train_140.png', 'D:\\project2\\test2\\train\\A\\train_141.png', 'D:\\project2\\test2\\train\\A\\train_142.png', 'D:\\project2\\test2\\train\\A\\train_143.png', 'D:\\project2\\test2\\train\\A\\train_144.png', 'D:\\project2\\test2\\train\\A\\train_145.png', 'D:\\project2\\test2\\train\\A\\train_146.png', 'D:\\project2\\test2\\train\\A\\train_147.png', 'D:\\project2\\test2\\train\\A\\train_148.png', 'D:\\project2\\test2\\train\\A\\train_149.png', 'D:\\project2\\test2\\train\\A\\train_15.png', 'D:\\project2\\test2\\train\\A\\train_150.png', 'D:\\project2\\test2\\train\\A\\train_151.png', 'D:\\project2\\test2\\train\\A\\train_152.png', 'D:\\project2\\test2\\train\\A\\train_153.png', 'D:\\project2\\test2\\train\\A\\train_154.png', 'D:\\project2\\test2\\train\\A\\train_155.png', 'D:\\project2\\test2\\train\\A\\train_156.png', 'D:\\project2\\test2\\train\\A\\train_157.png', 'D:\\project2\\test2\\train\\A\\train_158.png', 'D:\\project2\\test2\\train\\A\\train_159.png', 'D:\\project2\\test2\\train\\A\\train_16.png', 'D:\\project2\\test2\\train\\A\\train_160.png', 'D:\\project2\\test2\\train\\A\\train_161.png', 'D:\\project2\\test2\\train\\A\\train_162.png', 'D:\\project2\\test2\\train\\A\\train_163.png', 'D:\\project2\\test2\\train\\A\\train_164.png', 'D:\\project2\\test2\\train\\A\\train_165.png', 'D:\\project2\\test2\\train\\A\\train_166.png', 'D:\\project2\\test2\\train\\A\\train_167.png', 'D:\\project2\\test2\\train\\A\\train_168.png', 'D:\\project2\\test2\\train\\A\\train_169.png', 'D:\\project2\\test2\\train\\A\\train_17.png', 'D:\\project2\\test2\\train\\A\\train_170.png', 'D:\\project2\\test2\\train\\A\\train_171.png', 'D:\\project2\\test2\\train\\A\\train_172.png', 'D:\\project2\\test2\\train\\A\\train_173.png', 'D:\\project2\\test2\\train\\A\\train_174.png', 'D:\\project2\\test2\\train\\A\\train_175.png', 'D:\\project2\\test2\\train\\A\\train_176.png', 'D:\\project2\\test2\\train\\A\\train_177.png', 'D:\\project2\\test2\\train\\A\\train_178.png', 'D:\\project2\\test2\\train\\A\\train_179.png', 'D:\\project2\\test2\\train\\A\\train_18.png', 'D:\\project2\\test2\\train\\A\\train_180.png', 'D:\\project2\\test2\\train\\A\\train_181.png', 'D:\\project2\\test2\\train\\A\\train_182.png', 'D:\\project2\\test2\\train\\A\\train_183.png', 'D:\\project2\\test2\\train\\A\\train_184.png', 'D:\\project2\\test2\\train\\A\\train_185.png', 'D:\\project2\\test2\\train\\A\\train_186.png', 'D:\\project2\\test2\\train\\A\\train_187.png', 'D:\\project2\\test2\\train\\A\\train_188.png', 'D:\\project2\\test2\\train\\A\\train_189.png', 'D:\\project2\\test2\\train\\A\\train_19.png', 'D:\\project2\\test2\\train\\A\\train_190.png', 'D:\\project2\\test2\\train\\A\\train_191.png', 'D:\\project2\\test2\\train\\A\\train_192.png', 'D:\\project2\\test2\\train\\A\\train_193.png', 'D:\\project2\\test2\\train\\A\\train_194.png', 'D:\\project2\\test2\\train\\A\\train_195.png', 'D:\\project2\\test2\\train\\A\\train_196.png', 'D:\\project2\\test2\\train\\A\\train_197.png', 'D:\\project2\\test2\\train\\A\\train_198.png', 'D:\\project2\\test2\\train\\A\\train_199.png', 'D:\\project2\\test2\\train\\A\\train_2.png', 'D:\\project2\\test2\\train\\A\\train_20.png', 'D:\\project2\\test2\\train\\A\\train_200.png', 'D:\\project2\\test2\\train\\A\\train_201.png', 'D:\\project2\\test2\\train\\A\\train_202.png', 'D:\\project2\\test2\\train\\A\\train_203.png', 'D:\\project2\\test2\\train\\A\\train_204.png', 'D:\\project2\\test2\\train\\A\\train_205.png', 'D:\\project2\\test2\\train\\A\\train_206.png', 'D:\\project2\\test2\\train\\A\\train_207.png', 'D:\\project2\\test2\\train\\A\\train_208.png', 'D:\\project2\\test2\\train\\A\\train_209.png', 'D:\\project2\\test2\\train\\A\\train_21.png', 'D:\\project2\\test2\\train\\A\\train_210.png', 'D:\\project2\\test2\\train\\A\\train_211.png', 'D:\\project2\\test2\\train\\A\\train_212.png', 'D:\\project2\\test2\\train\\A\\train_213.png', 'D:\\project2\\test2\\train\\A\\train_214.png', 'D:\\project2\\test2\\train\\A\\train_215.png', 'D:\\project2\\test2\\train\\A\\train_216.png', 'D:\\project2\\test2\\train\\A\\train_217.png', 'D:\\project2\\test2\\train\\A\\train_218.png', 'D:\\project2\\test2\\train\\A\\train_219.png', 'D:\\project2\\test2\\train\\A\\train_22.png', 'D:\\project2\\test2\\train\\A\\train_220.png', 'D:\\project2\\test2\\train\\A\\train_221.png', 'D:\\project2\\test2\\train\\A\\train_222.png', 'D:\\project2\\test2\\train\\A\\train_223.png', 'D:\\project2\\test2\\train\\A\\train_224.png', 'D:\\project2\\test2\\train\\A\\train_225.png', 'D:\\project2\\test2\\train\\A\\train_226.png', 'D:\\project2\\test2\\train\\A\\train_227.png', 'D:\\project2\\test2\\train\\A\\train_228.png', 'D:\\project2\\test2\\train\\A\\train_229.png', 'D:\\project2\\test2\\train\\A\\train_23.png', 'D:\\project2\\test2\\train\\A\\train_230.png', 'D:\\project2\\test2\\train\\A\\train_231.png', 'D:\\project2\\test2\\train\\A\\train_232.png', 'D:\\project2\\test2\\train\\A\\train_233.png', 'D:\\project2\\test2\\train\\A\\train_234.png', 'D:\\project2\\test2\\train\\A\\train_235.png', 'D:\\project2\\test2\\train\\A\\train_236.png', 'D:\\project2\\test2\\train\\A\\train_237.png', 'D:\\project2\\test2\\train\\A\\train_238.png', 'D:\\project2\\test2\\train\\A\\train_239.png', 'D:\\project2\\test2\\train\\A\\train_24.png', 'D:\\project2\\test2\\train\\A\\train_240.png', 'D:\\project2\\test2\\train\\A\\train_241.png', 'D:\\project2\\test2\\train\\A\\train_242.png', 'D:\\project2\\test2\\train\\A\\train_243.png', 'D:\\project2\\test2\\train\\A\\train_244.png', 'D:\\project2\\test2\\train\\A\\train_245.png', 'D:\\project2\\test2\\train\\A\\train_246.png', 'D:\\project2\\test2\\train\\A\\train_247.png', 'D:\\project2\\test2\\train\\A\\train_248.png', 'D:\\project2\\test2\\train\\A\\train_249.png', 'D:\\project2\\test2\\train\\A\\train_25.png', 'D:\\project2\\test2\\train\\A\\train_250.png', 'D:\\project2\\test2\\train\\A\\train_251.png', 'D:\\project2\\test2\\train\\A\\train_252.png', 'D:\\project2\\test2\\train\\A\\train_253.png', 'D:\\project2\\test2\\train\\A\\train_254.png', 'D:\\project2\\test2\\train\\A\\train_255.png', 'D:\\project2\\test2\\train\\A\\train_256.png', 'D:\\project2\\test2\\train\\A\\train_257.png', 'D:\\project2\\test2\\train\\A\\train_258.png', 'D:\\project2\\test2\\train\\A\\train_259.png', 'D:\\project2\\test2\\train\\A\\train_26.png', 'D:\\project2\\test2\\train\\A\\train_260.png', 'D:\\project2\\test2\\train\\A\\train_261.png', 'D:\\project2\\test2\\train\\A\\train_262.png', 'D:\\project2\\test2\\train\\A\\train_263.png', 'D:\\project2\\test2\\train\\A\\train_264.png', 'D:\\project2\\test2\\train\\A\\train_265.png', 'D:\\project2\\test2\\train\\A\\train_266.png', 'D:\\project2\\test2\\train\\A\\train_267.png', 'D:\\project2\\test2\\train\\A\\train_268.png', 'D:\\project2\\test2\\train\\A\\train_269.png', 'D:\\project2\\test2\\train\\A\\train_27.png', 'D:\\project2\\test2\\train\\A\\train_270.png', 'D:\\project2\\test2\\train\\A\\train_271.png', 'D:\\project2\\test2\\train\\A\\train_272.png', 'D:\\project2\\test2\\train\\A\\train_273.png', 'D:\\project2\\test2\\train\\A\\train_274.png', 'D:\\project2\\test2\\train\\A\\train_275.png', 'D:\\project2\\test2\\train\\A\\train_276.png', 'D:\\project2\\test2\\train\\A\\train_277.png', 'D:\\project2\\test2\\train\\A\\train_278.png', 'D:\\project2\\test2\\train\\A\\train_279.png', 'D:\\project2\\test2\\train\\A\\train_28.png', 'D:\\project2\\test2\\train\\A\\train_280.png', 'D:\\project2\\test2\\train\\A\\train_281.png', 'D:\\project2\\test2\\train\\A\\train_282.png', 'D:\\project2\\test2\\train\\A\\train_283.png', 'D:\\project2\\test2\\train\\A\\train_284.png', 'D:\\project2\\test2\\train\\A\\train_285.png', 'D:\\project2\\test2\\train\\A\\train_286.png', 'D:\\project2\\test2\\train\\A\\train_287.png', 'D:\\project2\\test2\\train\\A\\train_288.png', 'D:\\project2\\test2\\train\\A\\train_289.png', 'D:\\project2\\test2\\train\\A\\train_29.png', 'D:\\project2\\test2\\train\\A\\train_290.png', 'D:\\project2\\test2\\train\\A\\train_291.png', 'D:\\project2\\test2\\train\\A\\train_292.png', 'D:\\project2\\test2\\train\\A\\train_293.png', 'D:\\project2\\test2\\train\\A\\train_294.png', 'D:\\project2\\test2\\train\\A\\train_295.png', 'D:\\project2\\test2\\train\\A\\train_296.png', 'D:\\project2\\test2\\train\\A\\train_297.png', 'D:\\project2\\test2\\train\\A\\train_298.png', 'D:\\project2\\test2\\train\\A\\train_299.png', 'D:\\project2\\test2\\train\\A\\train_3.png', 'D:\\project2\\test2\\train\\A\\train_30.png', 'D:\\project2\\test2\\train\\A\\train_300.png', 'D:\\project2\\test2\\train\\A\\train_301.png', 'D:\\project2\\test2\\train\\A\\train_302.png', 'D:\\project2\\test2\\train\\A\\train_303.png', 'D:\\project2\\test2\\train\\A\\train_304.png', 'D:\\project2\\test2\\train\\A\\train_305.png', 'D:\\project2\\test2\\train\\A\\train_306.png', 'D:\\project2\\test2\\train\\A\\train_307.png', 'D:\\project2\\test2\\train\\A\\train_308.png', 'D:\\project2\\test2\\train\\A\\train_309.png', 'D:\\project2\\test2\\train\\A\\train_31.png', 'D:\\project2\\test2\\train\\A\\train_310.png', 'D:\\project2\\test2\\train\\A\\train_311.png', 'D:\\project2\\test2\\train\\A\\train_312.png', 'D:\\project2\\test2\\train\\A\\train_313.png', 'D:\\project2\\test2\\train\\A\\train_314.png', 'D:\\project2\\test2\\train\\A\\train_315.png', 'D:\\project2\\test2\\train\\A\\train_316.png', 'D:\\project2\\test2\\train\\A\\train_317.png', 'D:\\project2\\test2\\train\\A\\train_318.png', 'D:\\project2\\test2\\train\\A\\train_319.png', 'D:\\project2\\test2\\train\\A\\train_32.png', 'D:\\project2\\test2\\train\\A\\train_320.png', 'D:\\project2\\test2\\train\\A\\train_321.png', 'D:\\project2\\test2\\train\\A\\train_322.png', 'D:\\project2\\test2\\train\\A\\train_323.png', 'D:\\project2\\test2\\train\\A\\train_324.png', 'D:\\project2\\test2\\train\\A\\train_325.png', 'D:\\project2\\test2\\train\\A\\train_326.png', 'D:\\project2\\test2\\train\\A\\train_327.png', 'D:\\project2\\test2\\train\\A\\train_328.png', 'D:\\project2\\test2\\train\\A\\train_329.png', 'D:\\project2\\test2\\train\\A\\train_33.png', 'D:\\project2\\test2\\train\\A\\train_330.png', 'D:\\project2\\test2\\train\\A\\train_331.png', 'D:\\project2\\test2\\train\\A\\train_332.png', 'D:\\project2\\test2\\train\\A\\train_333.png', 'D:\\project2\\test2\\train\\A\\train_334.png', 'D:\\project2\\test2\\train\\A\\train_335.png', 'D:\\project2\\test2\\train\\A\\train_336.png', 'D:\\project2\\test2\\train\\A\\train_337.png', 'D:\\project2\\test2\\train\\A\\train_338.png', 'D:\\project2\\test2\\train\\A\\train_339.png', 'D:\\project2\\test2\\train\\A\\train_34.png', 'D:\\project2\\test2\\train\\A\\train_340.png', 'D:\\project2\\test2\\train\\A\\train_341.png', 'D:\\project2\\test2\\train\\A\\train_342.png', 'D:\\project2\\test2\\train\\A\\train_343.png', 'D:\\project2\\test2\\train\\A\\train_344.png', 'D:\\project2\\test2\\train\\A\\train_345.png', 'D:\\project2\\test2\\train\\A\\train_346.png', 'D:\\project2\\test2\\train\\A\\train_347.png', 'D:\\project2\\test2\\train\\A\\train_348.png', 'D:\\project2\\test2\\train\\A\\train_349.png', 'D:\\project2\\test2\\train\\A\\train_35.png', 'D:\\project2\\test2\\train\\A\\train_350.png', 'D:\\project2\\test2\\train\\A\\train_351.png', 'D:\\project2\\test2\\train\\A\\train_352.png', 'D:\\project2\\test2\\train\\A\\train_353.png', 'D:\\project2\\test2\\train\\A\\train_354.png', 'D:\\project2\\test2\\train\\A\\train_355.png', 'D:\\project2\\test2\\train\\A\\train_356.png', 'D:\\project2\\test2\\train\\A\\train_357.png', 'D:\\project2\\test2\\train\\A\\train_358.png', 'D:\\project2\\test2\\train\\A\\train_359.png', 'D:\\project2\\test2\\train\\A\\train_36.png', 'D:\\project2\\test2\\train\\A\\train_360.png', 'D:\\project2\\test2\\train\\A\\train_361.png', 'D:\\project2\\test2\\train\\A\\train_362.png', 'D:\\project2\\test2\\train\\A\\train_363.png', 'D:\\project2\\test2\\train\\A\\train_364.png', 'D:\\project2\\test2\\train\\A\\train_365.png', 'D:\\project2\\test2\\train\\A\\train_366.png', 'D:\\project2\\test2\\train\\A\\train_367.png', 'D:\\project2\\test2\\train\\A\\train_368.png', 'D:\\project2\\test2\\train\\A\\train_369.png', 'D:\\project2\\test2\\train\\A\\train_37.png', 'D:\\project2\\test2\\train\\A\\train_370.png', 'D:\\project2\\test2\\train\\A\\train_371.png', 'D:\\project2\\test2\\train\\A\\train_372.png', 'D:\\project2\\test2\\train\\A\\train_373.png', 'D:\\project2\\test2\\train\\A\\train_374.png', 'D:\\project2\\test2\\train\\A\\train_375.png', 'D:\\project2\\test2\\train\\A\\train_376.png', 'D:\\project2\\test2\\train\\A\\train_377.png', 'D:\\project2\\test2\\train\\A\\train_378.png', 'D:\\project2\\test2\\train\\A\\train_379.png', 'D:\\project2\\test2\\train\\A\\train_38.png', 'D:\\project2\\test2\\train\\A\\train_380.png', 'D:\\project2\\test2\\train\\A\\train_381.png', 'D:\\project2\\test2\\train\\A\\train_382.png', 'D:\\project2\\test2\\train\\A\\train_383.png', 'D:\\project2\\test2\\train\\A\\train_384.png', 'D:\\project2\\test2\\train\\A\\train_385.png', 'D:\\project2\\test2\\train\\A\\train_386.png', 'D:\\project2\\test2\\train\\A\\train_387.png', 'D:\\project2\\test2\\train\\A\\train_388.png', 'D:\\project2\\test2\\train\\A\\train_389.png', 'D:\\project2\\test2\\train\\A\\train_39.png', 'D:\\project2\\test2\\train\\A\\train_390.png', 'D:\\project2\\test2\\train\\A\\train_391.png', 'D:\\project2\\test2\\train\\A\\train_392.png', 'D:\\project2\\test2\\train\\A\\train_393.png', 'D:\\project2\\test2\\train\\A\\train_394.png', 'D:\\project2\\test2\\train\\A\\train_395.png', 'D:\\project2\\test2\\train\\A\\train_396.png', 'D:\\project2\\test2\\train\\A\\train_397.png', 'D:\\project2\\test2\\train\\A\\train_398.png', 'D:\\project2\\test2\\train\\A\\train_399.png', 'D:\\project2\\test2\\train\\A\\train_4.png', 'D:\\project2\\test2\\train\\A\\train_40.png', 'D:\\project2\\test2\\train\\A\\train_400.png', 'D:\\project2\\test2\\train\\A\\train_401.png', 'D:\\project2\\test2\\train\\A\\train_402.png', 'D:\\project2\\test2\\train\\A\\train_403.png', 'D:\\project2\\test2\\train\\A\\train_404.png', 'D:\\project2\\test2\\train\\A\\train_405.png', 'D:\\project2\\test2\\train\\A\\train_406.png', 'D:\\project2\\test2\\train\\A\\train_407.png', 'D:\\project2\\test2\\train\\A\\train_408.png', 'D:\\project2\\test2\\train\\A\\train_409.png', 'D:\\project2\\test2\\train\\A\\train_41.png', 'D:\\project2\\test2\\train\\A\\train_410.png', 'D:\\project2\\test2\\train\\A\\train_411.png', 'D:\\project2\\test2\\train\\A\\train_412.png', 'D:\\project2\\test2\\train\\A\\train_413.png', 'D:\\project2\\test2\\train\\A\\train_414.png', 'D:\\project2\\test2\\train\\A\\train_415.png', 'D:\\project2\\test2\\train\\A\\train_416.png', 'D:\\project2\\test2\\train\\A\\train_417.png', 'D:\\project2\\test2\\train\\A\\train_418.png', 'D:\\project2\\test2\\train\\A\\train_419.png', 'D:\\project2\\test2\\train\\A\\train_42.png', 'D:\\project2\\test2\\train\\A\\train_420.png', 'D:\\project2\\test2\\train\\A\\train_421.png', 'D:\\project2\\test2\\train\\A\\train_422.png', 'D:\\project2\\test2\\train\\A\\train_423.png', 'D:\\project2\\test2\\train\\A\\train_424.png', 'D:\\project2\\test2\\train\\A\\train_425.png', 'D:\\project2\\test2\\train\\A\\train_426.png', 'D:\\project2\\test2\\train\\A\\train_427.png', 'D:\\project2\\test2\\train\\A\\train_428.png', 'D:\\project2\\test2\\train\\A\\train_429.png', 'D:\\project2\\test2\\train\\A\\train_43.png', 'D:\\project2\\test2\\train\\A\\train_430.png', 'D:\\project2\\test2\\train\\A\\train_431.png', 'D:\\project2\\test2\\train\\A\\train_432.png', 'D:\\project2\\test2\\train\\A\\train_433.png', 'D:\\project2\\test2\\train\\A\\train_434.png', 'D:\\project2\\test2\\train\\A\\train_435.png', 'D:\\project2\\test2\\train\\A\\train_436.png', 'D:\\project2\\test2\\train\\A\\train_437.png', 'D:\\project2\\test2\\train\\A\\train_438.png', 'D:\\project2\\test2\\train\\A\\train_439.png', 'D:\\project2\\test2\\train\\A\\train_44.png', 'D:\\project2\\test2\\train\\A\\train_440.png', 'D:\\project2\\test2\\train\\A\\train_441.png', 'D:\\project2\\test2\\train\\A\\train_442.png', 'D:\\project2\\test2\\train\\A\\train_443.png', 'D:\\project2\\test2\\train\\A\\train_444.png', 'D:\\project2\\test2\\train\\A\\train_445.png', 'D:\\project2\\test2\\train\\A\\train_45.png', 'D:\\project2\\test2\\train\\A\\train_46.png', 'D:\\project2\\test2\\train\\A\\train_47.png', 'D:\\project2\\test2\\train\\A\\train_48.png', 'D:\\project2\\test2\\train\\A\\train_49.png', 'D:\\project2\\test2\\train\\A\\train_5.png', 'D:\\project2\\test2\\train\\A\\train_50.png', 'D:\\project2\\test2\\train\\A\\train_51.png', 'D:\\project2\\test2\\train\\A\\train_52.png', 'D:\\project2\\test2\\train\\A\\train_53.png', 'D:\\project2\\test2\\train\\A\\train_54.png', 'D:\\project2\\test2\\train\\A\\train_55.png', 'D:\\project2\\test2\\train\\A\\train_56.png', 'D:\\project2\\test2\\train\\A\\train_57.png', 'D:\\project2\\test2\\train\\A\\train_58.png', 'D:\\project2\\test2\\train\\A\\train_59.png', 'D:\\project2\\test2\\train\\A\\train_6.png', 'D:\\project2\\test2\\train\\A\\train_60.png', 'D:\\project2\\test2\\train\\A\\train_61.png', 'D:\\project2\\test2\\train\\A\\train_62.png', 'D:\\project2\\test2\\train\\A\\train_63.png', 'D:\\project2\\test2\\train\\A\\train_64.png', 'D:\\project2\\test2\\train\\A\\train_65.png', 'D:\\project2\\test2\\train\\A\\train_66.png', 'D:\\project2\\test2\\train\\A\\train_67.png', 'D:\\project2\\test2\\train\\A\\train_68.png', 'D:\\project2\\test2\\train\\A\\train_69.png', 'D:\\project2\\test2\\train\\A\\train_7.png', 'D:\\project2\\test2\\train\\A\\train_70.png', 'D:\\project2\\test2\\train\\A\\train_71.png', 'D:\\project2\\test2\\train\\A\\train_72.png', 'D:\\project2\\test2\\train\\A\\train_73.png', 'D:\\project2\\test2\\train\\A\\train_74.png', 'D:\\project2\\test2\\train\\A\\train_75.png', 'D:\\project2\\test2\\train\\A\\train_76.png', 'D:\\project2\\test2\\train\\A\\train_77.png', 'D:\\project2\\test2\\train\\A\\train_78.png', 'D:\\project2\\test2\\train\\A\\train_79.png', 'D:\\project2\\test2\\train\\A\\train_8.png', 'D:\\project2\\test2\\train\\A\\train_80.png', 'D:\\project2\\test2\\train\\A\\train_81.png', 'D:\\project2\\test2\\train\\A\\train_82.png', 'D:\\project2\\test2\\train\\A\\train_83.png', 'D:\\project2\\test2\\train\\A\\train_84.png', 'D:\\project2\\test2\\train\\A\\train_85.png', 'D:\\project2\\test2\\train\\A\\train_86.png', 'D:\\project2\\test2\\train\\A\\train_87.png', 'D:\\project2\\test2\\train\\A\\train_88.png', 'D:\\project2\\test2\\train\\A\\train_89.png', 'D:\\project2\\test2\\train\\A\\train_9.png', 'D:\\project2\\test2\\train\\A\\train_90.png', 'D:\\project2\\test2\\train\\A\\train_91.png', 'D:\\project2\\test2\\train\\A\\train_92.png', 'D:\\project2\\test2\\train\\A\\train_93.png', 'D:\\project2\\test2\\train\\A\\train_94.png', 'D:\\project2\\test2\\train\\A\\train_95.png', 'D:\\project2\\test2\\train\\A\\train_96.png', 'D:\\project2\\test2\\train\\A\\train_97.png', 'D:\\project2\\test2\\train\\A\\train_98.png', 'D:\\project2\\test2\\train\\A\\train_99.png']
dataset [ChangeDetectionDataset] was created
Traceback (most recent call last):
  File "D:\project2\STANet-master\train.py", line 170, in <module>
    miou_current = val(opt, model)
  File "D:\project2\STANet-master\train.py", line 86, in val
    score = model.test(val=True)           # run inference
  File "D:\project2\STANet-master\models\CDF0_model.py", line 79, in test
    metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy())
  File "D:\project2\STANet-master\util\metrics.py", line 121, in update
    self.confusion_matrix += self.__fast_hist(lt.flatten(), lp.flatten())
  File "D:\project2\STANet-master\util\metrics.py", line 108, in __fast_hist
    hist = np.bincount(self.num_classes * label_gt[mask].astype(int) + label_pred[mask],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 4194304 but corresponding boolean dimension is 65536

这是什么原因？

**Comment by git1812220729** [comment]
I also encountered the same problem:"IndexError: boolean index did not match indexed array along dimension 0; dimension is 67108864 but corresponding boolean dimension is 1048576". Is there any good solution?

**Comment by 315133494** [comment]
请问有解决问题了吗

**Comment by ABCD121-SOURCE** [comment]
no，
&nbsp;


蒋超
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月12日(星期天) 下午4:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [justchenhao/STANet] 每次运行到epoch5就开始报错 (Issue #100)





 
请问有解决问题了吗

**Comment by Aoldcat1997** [comment]
it may be f_c seting,the output channel of  net is diference with labe

**Comment by wanglj-zzu** [comment]
def test(self, val=False):
        with torch.no_grad():
            self.forward()
            self.compute_visuals()
            if val:  # 返回score
                from util.metrics import RunningMetrics
                metrics = RunningMetrics(self.n_class)
                pred = self.pred_L.long()

                print(f"label_gt shape: {self.L.shape}, label_pred shape: {pred.shape}")

                metrics.update(self.L.detach().cpu().numpy(), pred.detach().cpu().numpy())
                scores = metrics.get_cm()
                return scores
            else:
                return self.pred_L.long()


在评估阶段，我写了段打印代码，打印出的label_gt shape: torch.Size([4, 1, 256, 256]), label_pred shape: torch.Size([4, 64, 256, 256]) 。所以说明经过PAM模块得到的特征图在通道数上没有进行后续处理，预测标签（64*256*256）与真值标签（1*64*64）直接计算混淆矩阵造成布尔维度（boolean dimension）不匹配的错误。

**Comment by hhgps** [comment]
ds=1 |2 | 4 , have a try..
