### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 64.00 GiB (GPU 0; 6.00 GiB total capacity; 402.79 MiB already allocated; 3.81 GiB free; 498.00 MiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by louxiantuo** [justchenhao/STANet#12]
64GiB out of memory? what......

**Comment by louxiantuo** [comment]
Traceback (most recent call last):
  File "./train.py", line 165, in <module>
    miou_current = val(opt, model)
  File "./train.py", line 85, in val
    score = model.test(val=True)           # run inference
  File "D:\xunleiDownload\STANet-master\models\CDFA_model.py", line 73, in test
    self.forward()
  File "D:\xunleiDownload\STANet-master\models\CDFA_model.py", line 90, in forward
    self.feat_A, self.feat_B = self.netA(self.feat_A,self.feat_B)
  File "D:\Software\anaconda3\envs\pytorch_gpu\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\xunleiDownload\STANet-master\models\backbone.py", line 46, in forward
    x = self.Self_Att(x)
  File "D:\Software\anaconda3\envs\pytorch_gpu\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\xunleiDownload\STANet-master\models\BAM.py", line 37, in forward
    energy = torch.bmm(proj_query, proj_key)  # transpose check
RuntimeError: CUDA out of memory. Tried to allocate 64.00 GiB (GPU 0; 6.00 GiB total capacity; 404.79 MiB already allocated; 3.84 GiB free; 470.00 MiB reserved in total by PyTorch)

**Comment by raminrahimi6970** [comment]
Hi 
Edit your batch-size to 4 or 2 or less

**Comment by justchenhao** [comment]
Has it fixed? Cause I could run the PAM on the GPU 1080Ti with the cropsize=256 and batchsize=4.

**Comment by louxiantuo** [comment]
Have you changed the picture of val to 256*256?

**Comment by justchenhao** [comment]
@louxiantuo Yes, all the picture has been cropped to the size of 256*256.

**Comment by louxiantuo** [comment]
> @louxiantuo Yes, all the picture has been cropped to the size of 256*256.

Do I need to write a script to process the pictures directly into 256*256? I am talking about val pictures.

**Comment by justchenhao** [comment]
@louxiantuo. Yes, the Val pictures also need to be cropped into 256*256, which lets the GPU handle the PAM memory consumption.  If you have unlimited memory of GPU, you could directly process the original pictures with a size of 1024*1024.

**Comment by justchenhao** [comment]
Close for now. Feel free to reopen if you still have questions.
