### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'weighted'

### ISSUE THREAD

**Issue by hktxt** [justchenhao/STANet#16]
Traceback (most recent call last):
  File "F:/STANet-master/train.py", line 109, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "F:\STANet-master\models\__init__.py", line 65, in create_model
    instance = model(opt)
  File "F:\STANet-master\models\CDFA_model.py", line 53, in __init__
    self.isweighted = opt.weighted
AttributeError: 'Namespace' object has no attribute 'weighted'

this caused: [CDFA_model.py line 53](https://github.com/justchenhao/STANet/blob/master/models/CDFA_model.py#L53)
`self.isweighted = opt.weighted`
no attribute 'weighted' specified in base_options.py/train_options.py

**Comment by justchenhao** [comment]
Greet! You could just delete this row.
