### ISSUE TITLE
About the test

### ISSUE THREAD

**Issue by wangshihuang** [justchenhao/STANet#21]
hello!

**Comment by wangshihuang** [comment]
Traceback (most recent call last):
  File "E:/abc/STANet-master/val.py", line 95, in <module>
    val(opt)
  File "E:/abc/STANet-master/val.py", line 61, in val
    score = model.test(val=True)  # run inference return confusion_matrix
  File "E:\abc\STANet-master\models\CDFA_model.py", line 73, in test
    self.forward()
  File "E:\abc\STANet-master\models\CDFA_model.py", line 89, in forward
    self.feat_A, self.feat_B = self.netA(self.feat_A, self.feat_B)
  File "D:\anaconda3\envs\keras\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\abc\STANet-master\models\backbone.py", line 46, in forward
    x = self.Self_Att(x)
  File "D:\anaconda3\envs\keras\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\abc\STANet-master\models\PAM2.py", line 157, in forward
    priors = [stage(feats) for stage in self.stages]
  File "E:\abc\STANet-master\models\PAM2.py", line 157, in <listcomp>
    priors = [stage(feats) for stage in self.stages]
  File "D:\anaconda3\envs\keras\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\abc\STANet-master\models\PAM2.py", line 102, in forward
    context_locals = func(v_locals, q_locals, k_locals)
  File "E:\abc\STANet-master\models\PAM2.py", line 82, in func
    sim_map = torch.bmm(query_local, key_local)  # batch matrix multiplication
RuntimeError: CUDA out of memory. Tried to allocate 64.00 GiB (GPU 0; 6.00 GiB total capacity; 240.92 MiB already allocated; 1.11 GiB free; 3.24 GiB reserved in total by PyTorch)
