### ISSUE TITLE
请问您的gpu是多大的，总是会爆下面的错误

### ISSUE THREAD

**Issue by xixi103** [justchenhao/STANet#50]
`Traceback (most recent call last):
  File "train.py", line 142, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/user/zxm/stanet/STANet-master1/STANet-master/models/CDFA_model.py", line 122, in optimize_parameters
    self.backward()                   # calculate graidents for G
  File "/home/user/zxm/stanet/STANet-master1/STANet-master/models/CDFA_model.py", line 108, in backward
    self.loss.backward()
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/user/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 3; 7.43 GiB total capacity; 5.01 GiB already allocated; 1.92 GiB free; 12.36 MiB cached)`

**Comment by zhijiejia** [comment]
可是设置 ds参数，在命令行中添加 --ds 4 或者 -ds 8 试试

**Comment by ddmice** [comment]
您的问题解决了吗？是怎么解决的呢？ 我的也是：RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 6.00 GiB total capacity; 2.98 GiB already allocated; 1.78 GiB free; 2.89 MiB cached)

**Comment by zhijiejia** [comment]
我估计是，在计算相似性矩阵的时候，输入的特征图尺寸过大，占用了比较多的显存，从而导致显存不足, 可以通过设置添加 ds参数，来讲特征图进行一次下采样，代码里默认ds=1, 可以试试添加 ' --ds 4 或者 --ds 8 '

**Comment by ddmice** [comment]
您是说batch size吗 我改成1都跑不成  ds是什么？请您指教

**Comment by ddmice** [comment]
您是指亲和力矩阵部分的代码吗？

**Comment by ddmice** [comment]
您好，我有些进展了，非常感谢您，我是变化检测方向的新学生。大四做毕设用到了这个，非常感谢。以后可以多多关注您的github学习；

**Comment by zhijiejia** [comment]
我也是大四学生，毕设变化检测。。。 嘿嘿嘿

**Comment by tan90du-sx** [comment]
您好，ds设置以后精度下降的很厉害，您有这个问题吗

**Comment by sungh66** [comment]
亲测加 --ds 4有用！！！

**Comment by tan90du-sx** [comment]
但是精度会下降，我下来精度还不如base

**Comment by zjbit** [comment]
ds=2在1080ti可以跑，1就不行，是不是得多卡模型并行呢？好像ds=2无法达到论文中的精度

**Comment by tan90du-sx** [comment]
我的情况也是如此，多卡并没有这个条件去做。您可以试试












孙雪
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月12日(周一) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [justchenhao/STANet] 请问您的gpu是多大的，总是会爆下面的错误 (#50)




 
ds=2在1080ti可以跑，1就不行，是不是得多卡模型并行呢？好像ds=2无法达到论文中的精度

**Comment by zjbit** [comment]
我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了

**Comment by nmxian** [comment]
你们跑的时候是先裁剪成256，还是在程序里随机选256的切片？为什么我跑base model的时候直接按GitHub里的命令跑，达不到论文精度，只有0.76，没有达到0.83

**Comment by Canoeof** [comment]
> 我也是大四学生，毕设变化检测。。。 嘿嘿嘿

你好，可以加qq1194571700交流一下吗，好像有不少人都是复现这个，可能会重复

**Comment by Canoeof** [comment]
> 您好，我有些进展了，非常感谢您，我是变化检测方向的新学生。大四做毕设用到了这个，非常感谢。以后可以多多关注您的github学习；

你好，我也是大四做毕设，复现了这个，可以交流一下吗，我怕重复了，qq1194571700

**Comment by nmxian** [comment]
> 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了

你达到了论文精度了吗？

**Comment by Canoeof** [comment]
> > 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了
> 
> 你达到了论文精度了吗？

只有0.739，你呢

**Comment by sungh66** [comment]
> > > 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了
> > 
> > 
> > 你达到了论文精度了吗？
> 
> 只有0.739，你呢

大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85

**Comment by nmxian** [comment]
> > > 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了
> > 
> > 
> > 你达到了论文精度了吗？
> 
> 只有0.739，你呢

事先裁成256的，value做测试集，base model bz=8，有0.810； bam： ds=2,，bz=4，也只有0.812

**Comment by nmxian** [comment]
> > > > 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了
> > > 
> > > 
> > > 你达到了论文精度了吗？
> > 
> > 
> > 只有0.739，你呢
> 
> 大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85

你是训练前把图片事先裁成128吗？还是按官网在程序中随机裁剪固定大小128？

**Comment by sungh66** [comment]
我是先离线裁剪256x256（overlap=0），然后在线随机裁剪128，不然会爆显存




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justchenhao/STANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [justchenhao/STANet] 请问您的gpu是多大的，总是会爆下面的错误 (#50)





     
我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了
  
你达到了论文精度了吗？
  
只有0.739，你呢
  
大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85
  
你是训练前把图片事先裁成128吗？还是按官网在程序中随机裁剪固定大小128？

**Comment by nmxian** [comment]
我去试下，谢谢！

**Comment by nmxian** [comment]
> 我是先离线裁剪256x256（overlap=0），然后在线随机裁剪128，不然会爆显存
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "justchenhao/STANet" ***@***.***&gt;; 发送时间:&nbsp;2021年4月23日(星期五) 下午4:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [justchenhao/STANet] 请问您的gpu是多大的，总是会爆下面的错误 (#50) 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了 你达到了论文精度了吗？ 只有0.739，你呢 大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85 你是训练前把图片事先裁成128吗？还是按官网在程序中随机裁剪固定大小128？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我去试下，谢谢！

**Comment by nmxian** [comment]
> 我是先离线裁剪256x256（overlap=0），然后在线随机裁剪128，不然会爆显存
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "justchenhao/STANet" ***@***.***&gt;; 发送时间:&nbsp;2021年4月23日(星期五) 下午4:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [justchenhao/STANet] 请问您的gpu是多大的，总是会爆下面的错误 (#50) 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了 你达到了论文精度了吗？ 只有0.739，你呢 大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85 你是训练前把图片事先裁成128吗？还是按官网在程序中随机裁剪固定大小128？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscrib

> > 我是先离线裁剪256x256（overlap=0），然后在线随机裁剪128，不然会爆显存
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "justchenhao/STANet" _**@**_._**>; 发送时间: 2021年4月23日(星期五) 下午4:21 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [justchenhao/STANet] 请问您的gpu是多大的，总是会爆下面的错误 (#50) 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了 你达到了论文精度了吗？ 只有0.739，你呢 大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85 你是训练前把图片事先裁成128吗？还是按官网在程序中随机裁剪固定大小128？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我去试下，谢谢

> 我是先离线裁剪256x256（overlap=0），然后在线随机裁剪128，不然会爆显存
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "justchenhao/STANet" ***@***.***&gt;; 发送时间:&nbsp;2021年4月23日(星期五) 下午4:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [justchenhao/STANet] 请问您的gpu是多大的，总是会爆下面的错误 (#50) 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了 你达到了论文精度了吗？ 只有0.739，你呢 大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85 你是训练前把图片事先裁成128吗？还是按官网在程序中随机裁剪固定大小128？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

老哥，能否提供下你的代码，我还是只有0.803，我qq2206936081

**Comment by Canoeof** [comment]
请问loss.py里面label是1和-1，而不是论文里提到的1，0，这是为什么呢

**Comment by sungh66** [comment]
> 请问loss.py里面label是1和-1，而不是论文里提到的1，0，这是为什么呢

对于loss的计算是一样的，代码中如果no-change就只剩loss1，如果change就只剩loss2，平衡正负样本比例，和论文中起到同样的效果

**Comment by gcg0210** [comment]
你们的pytorch是哪个版本的

**Comment by lilili-today** [comment]
> 我是先离线裁剪256x256（overlap=0），然后在线随机裁剪128，不然会爆显存
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "justchenhao/STANet" ***@***.***&gt;; 发送时间:&nbsp;2021年4月23日(星期五) 下午4:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [justchenhao/STANet] 请问您的gpu是多大的，总是会爆下面的错误 (#50) 我后来batch改成4，可以姿训练了，按照ds=1，效果就好很多了 你达到了论文精度了吗？ 只有0.739，你呢 大家可以crop_size和load_size都改成128，或者对图片切割数据增强，ds=1，batchasize=8，基本能复现论文精度，大概BAM到0.84，PAM到0.85 你是训练前把图片事先裁成128吗？还是按官网在程序中随机裁剪固定大小128？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，请问事前裁剪你是怎么实现的啊。我看论文里是将1024*1024的影像裁剪成16个256*256大小的影像。我不知道应该怎么裁剪。

**Comment by weizhiliang0520** [comment]
> 我估计是，在计算相似性矩阵的时候，输入的特征图尺寸过大，占用了比较多的显存，从而导致显存不足, 可以通过设置添加 ds参数，来讲特征图进行一次下采样，代码里默认ds=1, 可以试试添加 ' --ds 4 或者 --ds 8 '

  你好，我想问一下，跑代码的时候，baseline可以跑，等跑BAM时候，就出现问题，和你的一样。当我设置batch size 和ds很小的时候，但是我能够跑第一轮，后面不是每train完一轮以后，代码自动val 验证嘛，我的就卡了，out of memory 256G。
